FROM alpine:latest

COPY rootfs /

RUN apk update && apk add --no-cache libssl1.1 wget && \
    mkdir -p /tmp && \
    wget --no-check-certificate -P /tmp https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-arm && \
    mkdir -p /aircast && \
    cp /tmp/aircast-arm /aircast/aircast && \
    chmod a+x /aircast/aircast && \
    chmod a+x /aircast/start.sh && \
    rm -rf /tmp/* /var/cache/apk/*

ENTRYPOINT [ "/aircast/start.sh" ]