FROM arm32v7/debian:buster-slim

RUN apt update && apt install -y --no-install-recommends libssl1.1 wget && \
    wget --no-check-certificate -O /usr/local/bin/aircast "https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-arm" && \
    chmod a+x /usr/local/bin/aircast &&\
    rm -rf /tmp/* /var/cache/apk/* /var/tmp/*

CMD ["/usr/local/bin/aircast", "-r", "-Z", "-I"]
